# Generated by Django 6.0.5 on 2026-05-22 17:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cotizada', 'Cotizada'), ('pendiente_compra', 'Pedido pendiente de compra'), ('comprada', 'Comprada'), ('en_transito', 'En transito'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='cotizada', max_length=32)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('inicial_sugerida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.cliente')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='items/')),
                ('imagen_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('tienda', models.CharField(choices=[('shein', 'Shein'), ('amazon', 'Amazon'), ('aliexpress', 'AliExpress'), ('otro', 'Otro')], default='shein', max_length=32)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('descripcion', models.CharField(max_length=240)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor_version', models.CharField(choices=[('eeuu', 'EEUU'), ('espana', 'Espana'), ('venezuela', 'Venezuela'), ('colombia', 'Colombia'), ('otro', 'Otro')], default='eeuu', max_length=32)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orden')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(blank=True, max_length=80)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.orden')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=16)),
                ('categoria', models.CharField(choices=[('cobro_cliente', 'Cobro a cliente'), ('proveedor', 'Pago a proveedores'), ('sueldo', 'Sueldo'), ('gasolina', 'Gasolina'), ('delivery', 'Delivery'), ('flete', 'Flete'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('descripcion', models.CharField(max_length=220)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_caja', to='core.pago')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrecioReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shein_eeuu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shein_espana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shein_venezuela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shein_colombia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precios_referencia', to='core.itempedido')),
            ],
        ),
    ]
