# Generated by Django 6.0.5 on 2026-05-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itempedido_precio_shein_colombia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
