# Generated by Django 6.0.5 on 2026-05-23 15:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itempedido_imagen_url_alter_itempedido_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_transito', 'En transito'), ('recibido', 'Recibido'), ('cerrado', 'Cerrado')], default='preparando', max_length=32)),
                ('courier', models.CharField(blank=True, max_length=120)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('costo_flete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envio', to='core.movimientocaja')),
            ],
            options={
                'ordering': ['-fecha_creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_flete_asignado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_envio', to='core.envio')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='envio_asignado', to='core.orden')),
            ],
            options={
                'ordering': ['orden_id'],
            },
        ),
    ]
