# Generated by Django 6.0.5 on 2026-05-23 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_envio_ordenenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
