# Generated by Codex on 2026-05-23

import django.utils.timezone
from django.db import migrations, models


def normalizar_periodo_utilidad(apps, schema_editor):
    Envio = apps.get_model("core", "Envio")
    for envio in Envio.objects.all():
        base = envio.fecha_salida or django.utils.timezone.localdate()
        envio.periodo_utilidad = base.replace(day=1)
        envio.save(update_fields=["periodo_utilidad"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_orden_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="envio",
            name="fecha_pago_flete",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="periodo_utilidad",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(normalizar_periodo_utilidad, migrations.RunPython.noop),
    ]
